import { CanonicalCV } from '@/types/cv';
import { extractCanonicalCvFromText as ruleBasedFallbackExtract } from './cvExtractor';

const GEMINI_API_KEY =
  process.env.GEMINI_API_KEY ||
  process.env.NEXT_PUBLIC_GEMINI_API_KEY ||
  'AIzaSyB33tO93N2-PKflpVAmw9ooqdhxYIiwKgI';

export interface GeminiExtractionResult {
  cv: CanonicalCV;
  statusLog: string[];
  modelUsed: string;
  isFallback: boolean;
  errorMessage?: string;
}

/**
 * Uploads a file buffer to Gemini Resumable Upload API
 * Returns the file URI generated by Gemini
 */
export async function uploadBufferToGemini(
  fileBuffer: Buffer,
  fileName: string,
  mimeType: string,
  statusLog: string[]
): Promise<string | null> {
  try {
    const fileSize = fileBuffer.length;
    const logMsg = `Mengunggah file '${fileName}' (${Math.round(fileSize / 1024)} KB) ke Gemini Resumable File API...`;
    console.log(logMsg);
    statusLog.push(logMsg);

    // Step 1: Initiate upload
    const initRes = await fetch(
      `https://generativelanguage.googleapis.com/upload/v1beta/files?key=${GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: {
          'X-Goog-Upload-Protocol': 'resumable',
          'X-Goog-Upload-Command': 'start',
          'X-Goog-Upload-Header-Content-Length': fileSize.toString(),
          'X-Goog-Upload-Header-Content-Type': mimeType,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          file: {
            display_name: fileName,
          },
        }),
      }
    );

    if (!initRes.ok) {
      const errText = await initRes.text();
      const warnMsg = `Upload file Gemini gagal (HTTP ${initRes.status}): ${errText.substring(0, 100)}`;
      console.warn(warnMsg);
      statusLog.push(warnMsg);
      return null;
    }

    const uploadUrl = initRes.headers.get('x-goog-upload-url');
    if (!uploadUrl) {
      statusLog.push('Upload URL tidak ditemukan dari response header Gemini.');
      return null;
    }

    // Step 2: Upload file bytes as Uint8Array for Web Fetch API compatibility
    const uploadRes = await fetch(uploadUrl, {
      method: 'POST',
      headers: {
        'Content-Length': fileSize.toString(),
        'X-Goog-Upload-Offset': '0',
        'X-Goog-Upload-Command': 'upload, finalize',
      },
      body: new Uint8Array(fileBuffer),
    });

    if (!uploadRes.ok) {
      const errText = await uploadRes.text();
      const warnMsg = `Finalisasi upload file Gemini gagal (HTTP ${uploadRes.status}): ${errText.substring(0, 100)}`;
      console.warn(warnMsg);
      statusLog.push(warnMsg);
      return null;
    }

    const fileInfo = await uploadRes.json();
    const successMsg = `File berhasil diunggah ke Gemini File API (URI: ${fileInfo?.file?.name || fileInfo?.file?.uri})`;
    console.log(successMsg);
    statusLog.push(successMsg);

    return fileInfo?.file?.uri || null;
  } catch (error) {
    const errStr = `Error saat upload file ke Gemini: ${error instanceof Error ? error.message : String(error)}`;
    console.warn(errStr);
    statusLog.push(errStr);
    return null;
  }
}

/**
 * Extracts structured candidate data using Gemini AI (supports direct File API & text fallback)
 * Includes status logs and clear rate-limit/quota error diagnosis.
 */
export async function extractCvWithGeminiAI(
  rawCvText: string,
  fileBuffer?: Buffer,
  fileName?: string,
  mimeType?: string
): Promise<GeminiExtractionResult> {
  const statusLog: string[] = [];
  const modelsToTry = [
    'gemini-3-flash-preview',
    'gemini-2.0-flash',
    'gemini-3.1-flash-lite',
    'gemini-flash-latest',
  ];

  statusLog.push('Memulai proses ekstraksi & kualifikasi kandidat via Google Gemini AI...');

  const prompt = `
You are an Expert AI HR Specialist and Senior CV Analyst.
Analyze the provided candidate CV (file or text) and produce a fully qualified, structured JSON payload.

SPECIAL RULES FOR PORTFOLIO & PROJECTS:
- Extract all Portfolio Links, GitHub, Behance, Dribbble, LinkedIn, or Personal Portfolio URLs. DO NOT OMIT THEM.
- Thoroughly extract ALL Project Experiences (Nama Proyek, Deskripsi, Teknologi/Tech Stack, Role, Link Proyek) mentioned under work history or dedicated project sections.

REQUIRED JSON SCHEMA & RULES:
1. personal_information: Object containing:
   - full_name: string (Candidate Full Name)
   - email: string
   - phone: string
   - location: string
   - linkedin: string (Candidate LinkedIn URL if present)
   - portfolio_url: string (Candidate Portfolio, GitHub, Behance, or Personal Website link)
2. role: string (Candidate's primary role e.g., "Senior Fullstack JavaScript Developer", "IT Project Manager")
3. years_of_experience: string (Calculated total years & seniority string e.g., "Senior (7 Years)", "Middle (4 Years)", or "Junior (2 Years)")
4. seniority_level: "Junior" | "Middle" | "Senior" (Junior for 1-3 years, Middle for 3-5 years, Senior for 5+ years)
5. total_years_num: number (Total years calculated from work history)
6. about_me: string (CONCISE 2-3 sentence executive summary highlighting candidate role, total experience, core tech stack, and key impact)
7. summary: string (Same concise text as about_me)
8. work_experience: Array of objects containing:
   - id: string
   - company: string (Company Name e.g., "PT Aigen Global Teknologi", "Shopee", "PT Gudang Solusi")
   - position: string (Job Title / Position)
   - location: string
   - start_date: string (e.g., "Jan 2021" or "2021")
   - end_date: string (e.g., "Present" or "Dec 2023")
   - is_current: boolean
   - responsibilities: Array of strings (Full bullet point responsibilities and achievements extracted from source CV)
   - projects: Array of objects containing:
     - name: string (Project Name)
     - description: string (Project Description & Impact)
     - technologies: Array of strings (Tech stack used in project e.g. ["React", "Node.js", "PostgreSQL"])
     - role: string (Role in project)
     - link: string (Project live demo or repo link if present)
9. key_projects: Array of objects containing:
   - name: string
   - description: string
   - technologies: Array of strings
   - role: string
   - link: string
10. technical_qualifications: Array of strings (All technical skills, programming languages, tools, frameworks, databases e.g., ["Golang", "TypeScript", "React", "PostgreSQL", "Kafka", "Docker"])
11. education: Array of objects containing:
   - id: string
   - institution: string (University / Institute Name)
   - degree: string (Degree e.g., "Bachelor of Computer Science", "S1 Teknik Informatika")
   - field_of_study: string
12. certifications: Array of objects containing:
   - id: string
   - name: string (Certification Name e.g., "AWS Certified Solutions Architect")
   - issuer: string (Issuer e.g., "Amazon Web Services")
   - date: string

RAW CV TEXT AS REFERENCE:
"""
${rawCvText}
"""
`;

  // Attempt upload file to Gemini File API if buffer provided
  let fileUri: string | null = null;
  if (fileBuffer && fileName && mimeType) {
    fileUri = await uploadBufferToGemini(fileBuffer, fileName, mimeType, statusLog);
  }

  for (const modelName of modelsToTry) {
    try {
      const stepMsg = `Mengirim prompt & data CV ke model '${modelName}'...`;
      console.log(stepMsg);
      statusLog.push(stepMsg);

      const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;

      const parts: any[] = [];
      if (fileUri && mimeType) {
        parts.push({
          fileData: {
            mimeType: mimeType,
            fileUri: fileUri,
          },
        });
      }
      parts.push({ text: prompt });

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ role: 'user', parts }],
          generationConfig: {
            responseMimeType: 'application/json',
            temperature: 0.1,
          },
        }),
      });

      if (!response.ok) {
        let errDetail = '';
        try {
          const errJson = await response.json();
          errDetail = errJson?.error?.message || JSON.stringify(errJson);
        } catch {
          errDetail = await response.text();
        }

        let isQuotaError = response.status === 429 || errDetail.toLowerCase().includes('quota') || errDetail.toLowerCase().includes('resource_exhausted');
        const warnMsg = isQuotaError
          ? `⚠️ Kuota / Rate Limit Gemini terlampaui pada model '${modelName}' (HTTP ${response.status}: Batas Kuota Terlampaui). Mencoba model alternatif...`
          : `⚠️ Model '${modelName}' mengembalikan HTTP ${response.status}: ${errDetail.substring(0, 120)}. Mencoba model berikutnya...`;

        console.warn(warnMsg);
        statusLog.push(warnMsg);
        continue;
      }

      const data = await response.json();
      const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!responseText) {
        const emptyMsg = `Response dari model '${modelName}' kosong. Mencoba model berikutnya...`;
        console.warn(emptyMsg);
        statusLog.push(emptyMsg);
        continue;
      }

      const cleanJson = responseText.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
      const parsedData = JSON.parse(cleanJson);

      const qualifiedCv: CanonicalCV = {
        personal_information: {
          full_name: parsedData.personal_information?.full_name || 'Candidate',
          email: '',
          phone: '',
          location: parsedData.personal_information?.location || '',
          linkedin: parsedData.personal_information?.linkedin || '',
          portfolio_url: parsedData.personal_information?.portfolio_url || parsedData.personal_information?.website || '',
          website: parsedData.personal_information?.website || parsedData.personal_information?.portfolio_url || '',
        },
        role: parsedData.role || 'Professional Candidate',
        years_of_experience: parsedData.years_of_experience || 'Junior (1 Year)',
        seniority_level: parsedData.seniority_level || 'Junior',
        total_years_num: typeof parsedData.total_years_num === 'number' ? parsedData.total_years_num : 1,
        about_me: parsedData.about_me || parsedData.summary || '',
        summary: parsedData.summary || parsedData.about_me || '',
        work_experience: Array.isArray(parsedData.work_experience)
          ? parsedData.work_experience.map((job: any, index: number) => ({
              id: job.id || `job-ai-${index + 1}`,
              company: job.company || 'Enterprise Company',
              position: job.position || 'Professional Role',
              location: job.location || '',
              start_date: job.start_date || '',
              end_date: job.end_date || '',
              is_current: Boolean(job.is_current),
              responsibilities: Array.isArray(job.responsibilities) ? job.responsibilities : [],
              projects: Array.isArray(job.projects)
                ? job.projects.map((p: any) => ({
                    name: p.name || 'Project',
                    description: p.description || '',
                    technologies: Array.isArray(p.technologies) ? p.technologies : [],
                    role: p.role || '',
                    link: p.link || '',
                  }))
                : [],
            }))
          : [],
        key_projects: Array.isArray(parsedData.key_projects)
          ? parsedData.key_projects.map((p: any) => ({
              name: p.name || 'Project',
              description: p.description || '',
              technologies: Array.isArray(p.technologies) ? p.technologies : [],
              role: p.role || '',
              link: p.link || '',
            }))
          : [],
        technical_qualifications: Array.isArray(parsedData.technical_qualifications)
          ? parsedData.technical_qualifications
          : [],
        skills: {
          programming_languages: [],
          frameworks: [],
          databases: [],
          cloud: [],
          devops: [],
          tools: [],
          other: [],
        },
        certifications: Array.isArray(parsedData.certifications)
          ? parsedData.certifications.map((c: any, index: number) => ({
              id: c.id || `cert-ai-${index + 1}`,
              name: c.name || 'Certification',
              issuer: c.issuer || '',
              date: c.date || '',
            }))
          : [],
        education: Array.isArray(parsedData.education)
          ? parsedData.education.map((e: any, index: number) => ({
              id: e.id || `edu-ai-${index + 1}`,
              institution: e.institution || 'University',
              degree: e.degree || '',
              field_of_study: e.field_of_study || '',
              start_date: e.start_date || '',
              end_date: e.end_date || '',
            }))
          : [],
        languages: [],
        additional_information: [],
        meta: {
          extraction_confidence: 0.99,
          source_stats: {
            work_experience_count: parsedData.work_experience?.length || 0,
            skills_count: parsedData.technical_qualifications?.length || 0,
            certifications_count: parsedData.certifications?.length || 0,
            education_count: parsedData.education?.length || 0,
          },
        },
      };

      const successMsg = `✅ Analisis CV sukses menggunakan model '${modelName}'.`;
      console.log(successMsg);
      statusLog.push(successMsg);

      return {
        cv: qualifiedCv,
        statusLog,
        modelUsed: modelName,
        isFallback: false,
      };
    } catch (modelError) {
      const errStr = `Gagal pada model '${modelName}': ${modelError instanceof Error ? modelError.message : String(modelError)}`;
      console.warn(errStr);
      statusLog.push(errStr);
    }
  }

  const fallbackMsg = '⚠️ Seluruh endpoint Gemini AI tidak merespon atau kuota habis. Mengalihkan ke parser deterministik lokal.';
  console.warn(fallbackMsg);
  statusLog.push(fallbackMsg);

  const fallbackCv = ruleBasedFallbackExtract(rawCvText);

  return {
    cv: fallbackCv,
    statusLog,
    modelUsed: 'deterministic-fallback',
    isFallback: true,
    errorMessage: 'Quota limit or connection failure on Gemini AI endpoints.',
  };
}
